# Silent-NAS Docker Compose 配置
# 3 节点分布式集群 + NATS 消息总线

services:
  # ==================== NATS 消息总线 ====================
  nats:
    image: nats:2.10-alpine
    container_name: silent-nas-nats
    hostname: nats
    # 不将 4222 暴露到宿主机，避免与本机 NATS/端口冲突；仅暴露 8222 监控
    ports:
      - "8222:8222"  # HTTP 监控
    command:
      - "--http_port"
      - "8222"
      - "-m"
      - "8222"
    networks:
      - nas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz", "-O", "-"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # ==================== 节点 1 (种子节点) ====================
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: silent-nas:latest
    container_name: silent-nas-node1
    hostname: node1
    environment:
      # 服务配置
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      GRPC_PORT: 50051
      QUIC_PORT: 4433
      WEBDAV_PORT: 8081
      S3_PORT: 9001

      # 存储配置
      STORAGE_PATH: /data
      CHUNK_SIZE: 1048576

      # NATS 配置
      NATS_URL: nats://nats:4222
      NATS_TOPIC_PREFIX: bench.nas

      # S3 配置
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_ENABLE_AUTH: false

      # 认证配置
      AUTH_ENABLE: false
      JWT_SECRET: bench
      ACCESS_TOKEN_EXP: 3600
      REFRESH_TOKEN_EXP: 604800

      # 节点配置
      NODE_ENABLE: true
      SEED_NODES: ""
      HEARTBEAT_INTERVAL: 2
      NODE_TIMEOUT: 120

      # 同步配置
      AUTO_SYNC: true
      SYNC_INTERVAL: 2
      MAX_FILES_PER_SYNC: 200
      MAX_RETRIES: 3

      # 日志
      RUST_LOG: info
      RUST_BACKTRACE: 1
      ADVERTISE_HOST: node1
    ports:
      - "50051:50051"  # gRPC
      - "8080:8080"    # HTTP API
      - "8081:8081"    # WebDAV
      - "9001:9001"    # S3 API
      - "4433:4433"    # QUIC
    volumes:
      - node1-data:/data
    networks:
      - nas-network
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped

  # ==================== 节点 2 ====================
  node2:
    image: silent-nas:latest
    container_name: silent-nas-node2
    hostname: node2
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      GRPC_PORT: 50051
      QUIC_PORT: 4433
      WEBDAV_PORT: 8081
      S3_PORT: 9001
      STORAGE_PATH: /data
      CHUNK_SIZE: 1048576
      NATS_URL: nats://nats:4222
      NATS_TOPIC_PREFIX: bench.nas
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_ENABLE_AUTH: false
      AUTH_ENABLE: false
      JWT_SECRET: bench
      ACCESS_TOKEN_EXP: 3600
      REFRESH_TOKEN_EXP: 604800
      NODE_ENABLE: true
      SEED_NODES: "node1:50051"
      HEARTBEAT_INTERVAL: 2
      NODE_TIMEOUT: 120
      AUTO_SYNC: true
      SYNC_INTERVAL: 2
      MAX_FILES_PER_SYNC: 200
      MAX_RETRIES: 3
      RUST_LOG: info
      RUST_BACKTRACE: 1
      ADVERTISE_HOST: node2
    ports:
      - "50052:50051"
      - "8090:8080"
      - "8091:8081"
      - "9011:9001"
      - "4434:4433"
    volumes:
      - node2-data:/data
    networks:
      - nas-network
    depends_on:
      nats:
        condition: service_healthy
      node1:
        condition: service_started
    restart: unless-stopped

  # ==================== 节点 3 ====================
  node3:
    image: silent-nas:latest
    container_name: silent-nas-node3
    hostname: node3
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      GRPC_PORT: 50051
      QUIC_PORT: 4433
      WEBDAV_PORT: 8081
      S3_PORT: 9001
      STORAGE_PATH: /data
      CHUNK_SIZE: 1048576
      NATS_URL: nats://nats:4222
      NATS_TOPIC_PREFIX: bench.nas
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_ENABLE_AUTH: false
      AUTH_ENABLE: false
      JWT_SECRET: bench
      ACCESS_TOKEN_EXP: 3600
      REFRESH_TOKEN_EXP: 604800
      NODE_ENABLE: true
      SEED_NODES: "node1:50051"
      HEARTBEAT_INTERVAL: 2
      NODE_TIMEOUT: 120
      AUTO_SYNC: true
      SYNC_INTERVAL: 2
      MAX_FILES_PER_SYNC: 200
      MAX_RETRIES: 3
      RUST_LOG: info
      RUST_BACKTRACE: 1
      ADVERTISE_HOST: node3
    ports:
      - "50053:50051"
      - "8100:8080"
      - "8101:8081"
      - "9021:9001"
      - "4435:4433"
    volumes:
      - node3-data:/data
    networks:
      - nas-network
    depends_on:
      nats:
        condition: service_healthy
      node1:
        condition: service_started
    restart: unless-stopped

# ==================== 数据卷 ====================
volumes:
  node1-data:
    driver: local
  node2-data:
    driver: local
  node3-data:
    driver: local

# ==================== 网络 ====================
networks:
  nas-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
